"""Static constants."""

DEFAULT_INITIAL_CASH = 100_000.0
DEFAULT_HISTORY_PERIOD = "3mo"
DEFAULT_HISTORY_INTERVAL = "1d"
MIN_CONFIDENCE_THRESHOLD = 0.7
MAX_NEWS_ARTICLES = 20
REQUEST_TIMEOUT_SECONDS = 30
